### ISSUE TITLE
Idiots guide to get dbab and dnsmasq working on Ubuntu 17.04 on standalone laptop

### ISSUE THREAD

**Issue by ghost** [suntong/dbab--pre1.3.3#4]
I have installed dbab and dnsmasq via the package manager and I have done the following (as documented in the synopsis at [https://github.com/suntong/dbab](https://github.com/suntong/dbab)
```
/etc/init.d/dbab start
/usr/sbin/dbab-get-list
ln -s /usr/sbin/dbab-get-list /etc/cron.weekly/
```
But now I have no idea what to do next. [https://github.com/suntong/dbab/blob/master/src/dbab.md](https://github.com/suntong/dbab/blob/master/src/dbab.md) suggests using fixed IP addresses but this is not possible on a laptop that may connect to the internet via different networks (for example public wifi hotspots). So now what do I do? I don't even know if dnsmasq is working with dbab. Yes, I'm probably a stupid idiot but I haave spent about 3 days without any sleep googling and trying to understand how to get this thing working. Now I am at the end of my tether! Please help.

**Comment by suntong** [comment]
Hmm.... `dbab` is meant for SOHO server that serves to the whole LAN (local area network), not meant for the situation you described above. So you are exploring uncharted territory literally. 

Also, configure `dbab` is hard by itself as it integrates so many Linux server components. This is a job normally for system admins of your company for example, and the doc is written for such audience as well. That might be part of the reasons why you were having such a hard time. 

That being said, if your goal is do merely ad blocking, then it ***is*** possible to config `dbab` as such, but basically you are on your own. However, you may found the following articles helpful,

https://sfxpt.wordpress.com/2011/02/21/the-best-ad-blocking-method/  
https://sfxpt.wordpress.com/2014/01/05/the-best-ad-blocking-method-in-a-package/  
https://sfxpt.wordpress.com/tag/ad-blocking/

If after reading the above _detailed_ articles you are still have trouble figuring things out, then maybe browser’s adblock-plus extension is the best option for you, because understanding these articles and carrying them out does need system admins' knowledge as prerequisite, and I don't have the bandwidth to spell out everything for you.

**Comment by suntong** [comment]
closed for stale.
